# Generated by Django 2.2 on 2021-12-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collectibles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorlimit',
            name='collectible',
        ),
        migrations.AddField(
            model_name='monitorlimit',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Collectibles.device', verbose_name='设备'),
            preserve_default=False,
        ),
    ]
