# Generated by Django 2.2 on 2021-12-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collectibles', '0002_auto_20211213_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorlimit',
            name='device',
        ),
        migrations.AddField(
            model_name='monitorlimit',
            name='deviceId',
            field=models.CharField(default=0, max_length=36, verbose_name='设备号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Collectibles.monitorLimit', verbose_name='设备'),
        ),
    ]
